spring.application.name=user-service

server.port=8763

# Eureka Client Properties
eureka.instance.prefer-ip-address=true
eureka.client.fetch-register=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Postgres Properties
spring.datasource.driver-class-name=org.postgresql.Driver
#{DB_URL}
spring.datasource.url=jdbc:postgresql://localhost:5432/wtms_user_db  
#{DB_USER}
spring.datasource.username=admin
#{DB_PASSWORD}
spring.datasource.password=your_strong_password


# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Controls schema generation: 'update' will create tables based on your JPA entities.
spring.jpa.hibernate.ddl-auto=update
# Enable logging of SQL statements for debugging
spring.jpa.show-sql=true
# Set logging level for Hibernate
logging.level.org.hibernate.SQL=DEBUG


# Kafka
kafka.bootstrap.server=localhost:9092
kafka.consumer.group=user-group

app.security.internal-secret= yK8!pL3@xQ7#dT9$wF2^sR5&vM1*bN6(